services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server-orchestrator-backend
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=8080
      - DB_PATH=/data/database.sqlite
      - JWT_SECRET=${JWT_SECRET:-change-this-super-secret-jwt-key-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-12345678901234567890123456789012}
    volumes:
      - ./data:/data
      - ./backend/src:/app/src:ro
    networks:
      - orchestrator-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: server-orchestrator-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_WS_URL=ws://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - /app/node_modules
    networks:
      - orchestrator-net
    restart: unless-stopped

networks:
  orchestrator-net:
    driver: bridge

volumes:
  data:
    driver: local