services:
  mariadb:
    image: mariadb:11.2
    container_name: server-orchestrator-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-server_orchestrator}
      - MYSQL_USER=${DB_USER:-orchestrator}
      - MYSQL_PASSWORD=${DB_PASSWORD:-orchestratorpass}
      - MARIADB_CHARACTER_SET_SERVER=utf8mb4
      - MARIADB_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - orchestrator-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server-orchestrator-backend
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=8080
      - DB_TYPE=${DB_TYPE:-mysql}
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=${DB_USER:-orchestrator}
      - DB_PASSWORD=${DB_PASSWORD:-orchestratorpass}
      - DB_NAME=${DB_NAME:-server_orchestrator}
      - DB_PATH=/data/database.sqlite
      - JWT_SECRET=${JWT_SECRET:-change-this-super-secret-jwt-key-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-12345678901234567890123456789012}
    volumes:
      - ./data:/data
      - ./backend/src:/app/src:ro
    networks:
      - orchestrator-net
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: server-orchestrator-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_WS_URL=ws://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - /app/node_modules
    networks:
      - orchestrator-net
    restart: unless-stopped

networks:
  orchestrator-net:
    driver: bridge

volumes:
  data:
    driver: local
  mariadb_data:
    driver: local